import { Link } from 'react-router-dom';
import { HiOutlineSearch, HiOutlineLightningBolt, HiOutlineDocumentText, HiOutlineChartBar, HiOutlineChatAlt2, HiOutlineShieldCheck } from 'react-icons/hi';
import { RiGovernmentLine } from 'react-icons/ri';
import './Landing.css';

export default function Landing() {
  const features = [
    {
      icon: <HiOutlineSearch />,
      title: 'AI Eligibility Finder',
      desc: 'Describe yourself in plain language. Our AI instantly matches you with schemes you qualify for.',
      color: 'var(--primary)',
    },
    {
      icon: <HiOutlineChartBar />,
      title: 'Smart Ranking',
      desc: 'Schemes ranked by benefit amount, eligibility match, and application ease — see the best first.',
      color: 'var(--accent-green)',
    },
    {
      icon: <HiOutlineDocumentText />,
      title: 'Document Checklist',
      desc: 'Know exactly which documents you need. Never miss an application due to missing paperwork.',
      color: 'var(--accent)',
    },
    {
      icon: <HiOutlineLightningBolt />,
      title: 'Application Roadmap',
      desc: 'Step-by-step guidance generated by AI — what to do first, where to apply, and timeline.',
      color: 'var(--secondary)',
    },
    {
      icon: <HiOutlineChatAlt2 />,
      title: 'Ask Anything',
      desc: '"Can I apply without income certificate?" — get instant AI answers from scheme documents.',
      color: 'var(--accent-teal)',
    },
    {
      icon: <HiOutlineShieldCheck />,
      title: 'Benefit Gap Analysis',
      desc: 'Discover schemes you\'re missing out on. See your total potential benefits at a glance.',
      color: 'var(--saffron)',
    },
  ];

  const stats = [
    { value: '580+', label: 'Schemes' },
    { value: '6', label: 'AI Agents' },
    { value: '₹1.2L+', label: 'Avg. Benefits' },
    { value: '100%', label: 'Free' },
  ];

  return (
    <div className="landing">
      {/* Hero Section */}
      <section className="hero">
        <div className="hero-bg-elements">
          <div className="hero-orb hero-orb-1" />
          <div className="hero-orb hero-orb-2" />
          <div className="hero-orb hero-orb-3" />
        </div>

        <div className="container hero-content">
          <div className="hero-badge animate-fadeInUp">
            <RiGovernmentLine />
            <span>AI-Powered Government Scheme Discovery</span>
          </div>

          <h1 className="heading-xl animate-fadeInUp stagger-1">
            Find Every Scheme<br />
            <span className="text-gradient">You Deserve</span>
          </h1>

          <p className="hero-subtitle animate-fadeInUp stagger-2">
            Stop searching through 20 government websites. Tell us about yourself, 
            and our AI finds, ranks, and guides you through every scheme you qualify for.
          </p>

          <div className="hero-actions animate-fadeInUp stagger-3">
            <Link to="/analyze" className="btn btn-primary btn-lg">
              <HiOutlineSearch /> Find My Schemes
            </Link>
            <Link to="/chat" className="btn btn-secondary btn-lg">
              <HiOutlineChatAlt2 /> Ask AI
            </Link>
          </div>

          {/* Stats Bar */}
          <div className="hero-stats animate-fadeInUp stagger-4">
            {stats.map((s, i) => (
              <div key={i} className="hero-stat">
                <span className="hero-stat-value">{s.value}</span>
                <span className="hero-stat-label">{s.label}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="section how-it-works">
        <div className="container">
          <h2 className="heading-lg text-center">
            How It <span className="text-gradient">Works</span>
          </h2>
          <p className="section-subtitle text-center">
            From confusion to clarity in three simple steps
          </p>

          <div className="steps-grid">
            {[
              { num: '01', title: 'Describe Yourself', desc: 'Tell us your age, state, education, income — in plain language or through a form.' },
              { num: '02', title: 'AI Analyzes', desc: '6 AI agents process your profile: extract data, check eligibility, rank schemes, check documents.' },
              { num: '03', title: 'Get Your Roadmap', desc: 'See eligible schemes ranked by value, with documents needed and step-by-step application guide.' },
            ].map((step, i) => (
              <div key={i} className="step-card glass-card animate-fadeInUp" style={{ animationDelay: `${0.2 + i * 0.15}s` }}>
                <span className="step-num text-gradient">{step.num}</span>
                <h3 className="heading-sm">{step.title}</h3>
                <p className="step-desc">{step.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="section features-section">
        <div className="container">
          <h2 className="heading-lg text-center">
            Powered by <span className="text-gradient-warm">6 AI Agents</span>
          </h2>
          <p className="section-subtitle text-center">
            Not just search — intelligent analysis, ranking, and personalized guidance
          </p>

          <div className="features-grid">
            {features.map((f, i) => (
              <div key={i} className="feature-card glass-card animate-fadeInUp" style={{ animationDelay: `${0.1 + i * 0.1}s` }}>
                <div className="feature-icon" style={{ color: f.color, background: `${f.color}15` }}>
                  {f.icon}
                </div>
                <h3 className="heading-sm">{f.title}</h3>
                <p className="feature-desc">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="section cta-section">
        <div className="container">
          <div className="cta-card glass-card">
            <h2 className="heading-lg">Ready to discover your benefits?</h2>
            <p className="cta-desc">
              Join thousands of students who found scholarships and schemes they never knew about.
            </p>
            <Link to="/analyze" className="btn btn-primary btn-lg">
              Get Started — It&apos;s Free
            </Link>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="footer">
        <div className="container footer-inner">
          <div className="footer-brand">
            <RiGovernmentLine className="footer-icon" />
            <span>SarkariSahay</span>
          </div>
          <p className="footer-text">
            AI-powered government scheme discovery. Built with ❤️ for every Indian citizen.
          </p>
          <p className="footer-text footer-disclaimer">
            Data sourced from MyScheme, NSP, and official government portals.
          </p>
        </div>
      </footer>
    </div>
  );
}
